//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;assembly name=&quot;AssemblyToProcess&quot;&gt;
        ///  &lt;member name=&quot;T:AssemblyToProcess.SimpleClass&quot;&gt;
        ///    &lt;attribute ctor=&quot;M:JetBrains.Annotations.UsedImplicitlyAttribute.#ctor&quot; /&gt;
        ///  &lt;/member&gt;
        ///  &lt;member name=&quot;M:AssemblyToProcess.SimpleClass.#ctor&quot;&gt;
        ///    &lt;attribute ctor=&quot;M:JetBrains.Annotations.PublicAPIAttribute.#ctor&quot; /&gt;
        ///  &lt;/member&gt;
        ///  &lt;member name=&quot;M:AssemblyToProcess.SimpleClass.#ctor(System.Double)&quot;&gt;
        ///    &lt;attribute ctor=&quot;M:JetBrains.Annotations.PublicAPIAttribute.#ctor&quot; /&gt;
        ///    &lt;parameter name=&quot;protectedConstruct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedAnnotations {
            get {
                return ResourceManager.GetString("ExpectedAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;AssemblyToProcess&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:AssemblyToProcess.SimpleClass&quot;&gt;
        ///      &lt;summary&gt;
        ///            This is a simple class
        ///            &lt;p /&gt;&lt;c&gt;[UsedImplicitly]&lt;/c&gt;&lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;F:AssemblyToProcess.SimpleClass.privateField&quot;&gt;
        ///      &lt;summary&gt;
        ///            The private field
        ///            &lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;F:AssemblyToProcess.SimpleClass.publicField&quot;&gt;
        ///      &lt;summary&gt;
        ///            The pub [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedDocumentation {
            get {
                return ResourceManager.GetString("ExpectedDocumentation", resourceCulture);
            }
        }
    }
}
